### ISSUE TITLE
HAL and linker origins?

### ISSUE THREAD

**Issue by shabble** [lysergicenemy/emptyProject_gd32f303#1]
Hi,

Hopefully you don't mind my asking, but where did you come across the `gd32f30x_flash.ld` linker script, or did you write it from scratch?

There's a GD app note AN-033 that mentions it in passing, without ever actually saying where it can be found, and you seem to be the only place on the public internet with something vaguely resembling what I expect to find.

The reason I ask, and not just try using yours, is that I'm actually after the gd32f470 version, so if there are available in some SDK or other library bundle, would be really handy to know, rather than trying to bodge yours until it maybe works 😁 

Cheers

**Comment by lysergicenemy** [comment]
Hi. ld script and startup file were found on the github. The ld script was originally for a different version and was edited to fit my flash and RAM values.
I couldn't find the source code (ld/startup) for gcc from gigadevices.

**Comment by lysergicenemy** [comment]
> Hi,
> 
> Hopefully you don't mind my asking, but where did you come across the `gd32f30x_flash.ld` linker script, or did you write it from scratch?
> 
> There's a GD app note AN-033 that mentions it in passing, without ever actually saying where it can be found, and you seem to be the only place on the public internet with something vaguely resembling what I expect to find.
> 
> The reason I ask, and not just try using yours, is that I'm actually after the gd32f470 version, so if there are available in some SDK or other library bundle, would be really handy to know, rather than trying to bodge yours until it maybe works 😁
> 
> Cheers

Hi. ld script and startup file were found on the github. The ld script was originally for a different version and was edited to fit my flash and RAM values.
I couldn't find the source code (ld/startup) for gcc from gigadevices.

**Comment by shabble** [comment]
I did actually manage to get official copies via my GD distributor - not sure if I'm allowed to distribute them publicly, but they do have them if you contact support, in case it helps.

Thanks for the answer!
